version: "3.8"

x-aws-vpc: "vpc-0f793558f9bad7e46"

volumes:
  rabbitmq_data:

services:
  ####################################
  # Atomic Microservice: Item
  ####################################
  item:
    build:
      context: ./api/item
      dockerfile: item.Dockerfile
    image: "public.ecr.aws/m5u2v7u5/item:latest"
    restart: always
    env_file:
      - ".env"
    ports:
      - "5003:5003"

  ###################################
  # Atomic Microservice: Order
  ###################################
  order:
    build:
      context: ./api/order
      dockerfile: order.Dockerfile
    image: "public.ecr.aws/m5u2v7u5/order:latest"
    restart: always
    env_file:
      - ".env"
    ports:
      - "5002:5002"

  ####################################
  # Atomic Microservice: Error
  ####################################
  error:
    build:
      context: ./api/error
      dockerfile: error.Dockerfile
    image: theianchia/error
    restart: always
    env_file:
      - '.env'
    ports:
      - "5004:5004"

  ###################################
  # Atomic Microservice: User
  ###################################
  user:
    build:
      context: ./api/user
      dockerfile: user.Dockerfile
    image: theianchia/user
    restart: always
    env_file:
      - '.env'
    ports:
      - "5001:5001"

  ####################################
  # Atomic Microservice: SMS
  ####################################
  sms:
    build:
      context: ./api/sms
      dockerfile: sms.Dockerfile
    image: "public.ecr.aws/m5u2v7u5/sms:latest"
    depends_on:
      - rabbitmq
    restart: always
    env_file:
      - ".env"

  ###################################
  # Atomic Microservice: Place Order
  ###################################
  place_order:
    build:
      context: ./api/place_order
      dockerfile: place_order.Dockerfile
    image: "public.ecr.aws/m5u2v7u5/place_order:latest"
    depends_on:
      - order
      # - error
      - sms
      - rabbitmq
    restart: always
    env_file:
      - ".env"
    ports:
      - "5100:5100"

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: is458-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq

  ####################################
  # User Interface: User
  ####################################
  user-web:
    build:
      context: ./user-interfaces/user
      dockerfile: Dockerfile
    restart: always
    env_file:
      - '.env'
    ports:
      - "30001:8080"
